source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'AKTrakt iOS' do
	platform :ios, '8.0'
	pod "AKTrakt", :path => "../"
	pod "Alamofire"
	pod "AlamofireImage"
end

target 'AKTrakt tvOS' do
	platform :tvos, '9.0'
	pod "AKTrakt", :path => "../"
	pod "Alamofire"
	pod "AlamofireImage"
end

target 'AKTrakt_Tests' do
  pod "AKTrakt", :path => "../"
  pod "Alamofire"
end
