source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'AKTrakt_Example', :exclusive => true do
  pod "AKTrakt", :path => "../"
  pod "Alamofire"
end

target 'AKTrakt_Tests', :exclusive => true do
  pod "AKTrakt", :path => "../"
  pod "Alamofire"

  pod 'Quick', '~> 0.3.1'
  pod 'Nimble'
end
