source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'AKTrakt_iOS_Example', :exclusive => true do
	platform :ios, '8.0'
	pod "AKTrakt", :path => "../"
	pod "Alamofire"
end

target 'AKTrakt_TvOS_Example', :exclusive => true do
	platform :tvos, '9.0'
	pod "AKTrakt", :path => "../"
	pod "Alamofire"
end

target 'AKTrakt_Tests', :exclusive => true do
  pod "AKTrakt", :path => "../"
  pod "Alamofire"
end
